networks:
  barber-shop-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.254.0.0/29

services:
  postgres-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s
    networks:
      barber-shop-network:
        ipv4_address: 10.254.0.2

  spring-backend-bshop:
    build:
      context: ./barber-shop-api
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    environment:
    - DB_ADDRESS=10.254.0.2
    - DB_PORT=5432
    - DB_NAME=barber_shop
    - DB_USERNAME=postgres
    - DB_PASSWORD=postgres
    - JWT_SECRET=mysecretkey
    - CORS_ORIGIN=http://10.254.0.4:8080
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      barber-shop-network:
        ipv4_address: 10.254.0.3
  angular-nginx-frontend-bshop:
    build:
      context: ./barber-shop-ui
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      barber-shop-network:
        ipv4_address: 10.254.0.4